### ISSUE TITLE
Feature Request: Keep minor words in lowercase

### ISSUE THREAD

**Issue by Songyu-Wang** [grncdr/js-capitalize#16]
I know this is very complicated, but at least we can support a simplified version: `lowercase all articles (a, an, the), coordinating conjunctions (and, or, but, …) and (short) prepositions (in, on, for, up, …).` This should at least help with a decent amount of not grammar-focused computer science use cases

reference: https://titlecaseconverter.com/

**Comment by grncdr** [comment]
This is implemented and released in `2.0.4`. Because this library is used internationally by a variety of languages, the user is required to pass in their own `skipWord` callback or regular expression that determines if a word should be skipped. See [these test cases](https://github.com/grncdr/js-capitalize/blob/master/README.md?plain=1#L123-L142) for an example.
